grpc:
    port: 50051
dashboardServiceConfig:
    port: 9999
    acceptors: 5
    selectors: 10
    workers: 30
apiServiceConfig:
    port: 9998
    acceptors: 5
    selectors: 10
    workers: 30
    scheduledexecutor.threadpool.size: 1
